-- SQLite
insert into todo_item (text) values ('sit amet cursus id turpis integer');
insert into todo_item (text) values ('nulla nisl nunc nisl');
insert into todo_item (text) values ('sit amet nunc viverra dapibus nulla');
insert into todo_item (text) values ('sagittis sapien cum sociis natoque penatibus et magnis dis');
insert into todo_item (text) values ('quis justo maecenas rhoncus aliquam lacus morbi quis tortor');
insert into todo_item (text) values ('a nibh in quis justo maecenas rhoncus aliquam lacus');
insert into todo_item (text) values ('tempus sit amet sem fusce consequat nulla nisl nunc');
insert into todo_item (text) values ('vulputate nonummy maecenas tincidunt lacus at');
insert into todo_item (text) values ('eget massa tempor convallis nulla neque libero convallis');
insert into todo_item (text) values ('metus vitae ipsum aliquam non mauris');
insert into todo_item (text) values ('aliquam sit amet diam');
insert into todo_item (text) values ('id ornare imperdiet sapien urna');
insert into todo_item (text) values ('suspendisse potenti in eleifend quam a');
insert into todo_item (text) values ('curabitur at ipsum ac tellus');
insert into todo_item (text) values ('quis tortor id nulla ultrices aliquet');
insert into todo_item (text) values ('lacus at turpis donec');
insert into todo_item (text) values ('amet sapien dignissim vestibulum vestibulum ante ipsum primis in');
insert into todo_item (text) values ('eget vulputate ut ultrices vel augue vestibulum ante ipsum primis');
insert into todo_item (text) values ('volutpat dui maecenas tristique est et tempus semper');
insert into todo_item (text) values ('nec condimentum neque sapien placerat');
insert into todo_item (text) values ('posuere felis sed lacus morbi sem mauris laoreet ut');
insert into todo_item (text) values ('ornare consequat lectus in est risus');
insert into todo_item (text) values ('ut ultrices vel augue vestibulum ante ipsum primis');
insert into todo_item (text) values ('in sapien iaculis congue vivamus metus arcu adipiscing molestie');
insert into todo_item (text) values ('sapien iaculis congue vivamus metus');
insert into todo_item (text) values ('ligula pellentesque ultrices phasellus id sapien in sapien');
insert into todo_item (text) values ('nulla integer pede justo lacinia eget tincidunt eget tempus');
insert into todo_item (text) values ('quis augue luctus tincidunt nulla mollis molestie');
insert into todo_item (text) values ('magna bibendum imperdiet nullam orci pede venenatis');
insert into todo_item (text) values ('in purus eu magna vulputate luctus cum sociis');
insert into todo_item (text) values ('ipsum aliquam non mauris morbi non');
insert into todo_item (text) values ('id pretium iaculis diam erat fermentum justo');
insert into todo_item (text) values ('aenean fermentum donec ut mauris eget massa tempor convallis nulla');
insert into todo_item (text) values ('imperdiet nullam orci pede venenatis non');
insert into todo_item (text) values ('nam nulla integer pede');
insert into todo_item (text) values ('etiam faucibus cursus urna ut tellus nulla');
insert into todo_item (text) values ('nulla suscipit ligula in lacus curabitur at ipsum ac');
insert into todo_item (text) values ('tincidunt lacus at velit vivamus vel nulla eget');
insert into todo_item (text) values ('sit amet justo morbi ut odio cras mi pede');
insert into todo_item (text) values ('aenean lectus pellentesque eget nunc donec quis orci eget');
insert into todo_item (text) values ('tellus in sagittis dui vel nisl');
insert into todo_item (text) values ('nam tristique tortor eu pede');
insert into todo_item (text) values ('lobortis sapien sapien non mi integer ac');
insert into todo_item (text) values ('fusce posuere felis sed lacus morbi sem mauris');
insert into todo_item (text) values ('nec sem duis aliquam convallis nunc proin at turpis a');
insert into todo_item (text) values ('quis turpis sed ante vivamus tortor duis');
insert into todo_item (text) values ('nisl ut volutpat sapien arcu sed');
insert into todo_item (text) values ('sit amet consectetuer adipiscing elit proin');
insert into todo_item (text) values ('aliquam convallis nunc proin at turpis');
insert into todo_item (text) values ('vivamus tortor duis mattis egestas metus aenean fermentum');
insert into todo_item (text) values ('molestie lorem quisque ut');
insert into todo_item (text) values ('mi integer ac neque duis bibendum morbi non quam');
insert into todo_item (text) values ('pellentesque ultrices mattis odio donec vitae nisi nam ultrices');
insert into todo_item (text) values ('volutpat sapien arcu sed augue aliquam erat');
insert into todo_item (text) values ('amet lobortis sapien sapien non');
insert into todo_item (text) values ('curae mauris viverra diam vitae quam');
insert into todo_item (text) values ('velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit');
insert into todo_item (text) values ('mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor');
insert into todo_item (text) values ('condimentum neque sapien placerat');
insert into todo_item (text) values ('justo sollicitudin ut suscipit a feugiat et eros');
insert into todo_item (text) values ('egestas metus aenean fermentum donec ut mauris eget massa');
insert into todo_item (text) values ('lacinia sapien quis libero');
insert into todo_item (text) values ('est donec odio justo sollicitudin ut');
insert into todo_item (text) values ('maecenas pulvinar lobortis est');
insert into todo_item (text) values ('purus eu magna vulputate luctus');
insert into todo_item (text) values ('eu mi nulla ac enim in tempor turpis nec');
insert into todo_item (text) values ('in magna bibendum imperdiet nullam orci pede venenatis non sodales');
insert into todo_item (text) values ('sapien ut nunc vestibulum');
insert into todo_item (text) values ('curabitur at ipsum ac tellus semper interdum mauris');
insert into todo_item (text) values ('ligula nec sem duis aliquam convallis nunc proin at turpis');
insert into todo_item (text) values ('pulvinar nulla pede ullamcorper augue a suscipit nulla elit');
insert into todo_item (text) values ('odio condimentum id luctus nec molestie sed justo pellentesque');
insert into todo_item (text) values ('condimentum id luctus nec molestie sed justo pellentesque viverra');
insert into todo_item (text) values ('vel augue vestibulum rutrum');
insert into todo_item (text) values ('duis faucibus accumsan odio curabitur convallis duis consequat dui');
insert into todo_item (text) values ('vestibulum ante ipsum primis');
insert into todo_item (text) values ('pretium quis lectus suspendisse potenti in eleifend quam');
insert into todo_item (text) values ('viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum');
insert into todo_item (text) values ('morbi a ipsum integer a nibh in');
insert into todo_item (text) values ('montes nascetur ridiculus mus etiam vel augue');
insert into todo_item (text) values ('consequat lectus in est risus auctor sed tristique');
insert into todo_item (text) values ('diam nam tristique tortor');
insert into todo_item (text) values ('nisl nunc rhoncus dui vel sem sed sagittis nam congue');
insert into todo_item (text) values ('est donec odio justo');
insert into todo_item (text) values ('elit proin risus praesent lectus');
insert into todo_item (text) values ('condimentum id luctus nec molestie sed justo');
insert into todo_item (text) values ('porttitor lorem id ligula suspendisse ornare consequat');
insert into todo_item (text) values ('morbi sem mauris laoreet ut rhoncus');
insert into todo_item (text) values ('donec pharetra magna vestibulum');
insert into todo_item (text) values ('donec diam neque vestibulum eget');
insert into todo_item (text) values ('nullam varius nulla facilisi cras');
insert into todo_item (text) values ('id sapien in sapien iaculis');
insert into todo_item (text) values ('a nibh in quis justo maecenas rhoncus aliquam');
insert into todo_item (text) values ('sociis natoque penatibus et magnis');
insert into todo_item (text) values ('montes nascetur ridiculus mus etiam vel augue vestibulum');
insert into todo_item (text) values ('tincidunt in leo maecenas pulvinar');
insert into todo_item (text) values ('lectus in est risus auctor sed');
insert into todo_item (text) values ('leo maecenas pulvinar lobortis est phasellus sit amet');
insert into todo_item (text) values ('in lacus curabitur at ipsum ac tellus semper interdum mauris');
insert into todo_item (text) values ('ligula suspendisse ornare consequat lectus in');
insert into todo_item (text) values ('morbi non lectus aliquam sit amet diam in magna');
insert into todo_item (text) values ('interdum mauris non ligula pellentesque');
insert into todo_item (text) values ('vel accumsan tellus nisi');
insert into todo_item (text) values ('sollicitudin mi sit amet lobortis sapien');
insert into todo_item (text) values ('neque sapien placerat ante nulla justo aliquam');
insert into todo_item (text) values ('in magna bibendum imperdiet nullam orci pede');
insert into todo_item (text) values ('enim in tempor turpis nec euismod');
insert into todo_item (text) values ('ut odio cras mi pede malesuada in');
insert into todo_item (text) values ('pede ac diam cras pellentesque volutpat dui maecenas');
insert into todo_item (text) values ('vulputate luctus cum sociis');
insert into todo_item (text) values ('in faucibus orci luctus et ultrices');
insert into todo_item (text) values ('fusce congue diam id ornare imperdiet sapien');
insert into todo_item (text) values ('amet lobortis sapien sapien');
insert into todo_item (text) values ('sociis natoque penatibus et');
insert into todo_item (text) values ('lacus at turpis donec posuere metus');
insert into todo_item (text) values ('imperdiet nullam orci pede venenatis non sodales');
insert into todo_item (text) values ('eros vestibulum ac est lacinia nisi venenatis tristique fusce congue');
insert into todo_item (text) values ('amet justo morbi ut odio');
insert into todo_item (text) values ('pede lobortis ligula sit amet');
insert into todo_item (text) values ('enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin');
insert into todo_item (text) values ('sit amet nunc viverra dapibus nulla suscipit ligula in lacus');
insert into todo_item (text) values ('amet lobortis sapien sapien non');
insert into todo_item (text) values ('est donec odio justo sollicitudin ut suscipit a feugiat');
insert into todo_item (text) values ('cursus vestibulum proin eu mi nulla');
insert into todo_item (text) values ('convallis eget eleifend luctus');
insert into todo_item (text) values ('nulla neque libero convallis');
insert into todo_item (text) values ('nisl duis ac nibh fusce lacus');
insert into todo_item (text) values ('non pretium quis lectus suspendisse potenti');
insert into todo_item (text) values ('cubilia curae duis faucibus accumsan odio curabitur convallis duis');
insert into todo_item (text) values ('dui nec nisi volutpat eleifend donec ut dolor morbi vel');
insert into todo_item (text) values ('odio curabitur convallis duis consequat dui nec');
insert into todo_item (text) values ('sapien varius ut blandit non interdum in ante vestibulum ante');
insert into todo_item (text) values ('quam sollicitudin vitae consectetuer eget rutrum at');
insert into todo_item (text) values ('lobortis ligula sit amet eleifend pede libero');
insert into todo_item (text) values ('tempus vivamus in felis eu sapien cursus vestibulum');
insert into todo_item (text) values ('arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean');
insert into todo_item (text) values ('vehicula consequat morbi a ipsum integer a');
insert into todo_item (text) values ('lectus aliquam sit amet diam in magna bibendum imperdiet');
insert into todo_item (text) values ('penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus');
insert into todo_item (text) values ('duis ac nibh fusce lacus');
insert into todo_item (text) values ('at turpis donec posuere metus vitae ipsum');
insert into todo_item (text) values ('dapibus duis at velit eu');
insert into todo_item (text) values ('tincidunt eget tempus vel pede morbi porttitor lorem id ligula');
insert into todo_item (text) values ('sit amet sapien dignissim vestibulum vestibulum ante ipsum primis');
insert into todo_item (text) values ('maecenas tincidunt lacus at velit vivamus');
insert into todo_item (text) values ('interdum mauris non ligula pellentesque');
insert into todo_item (text) values ('venenatis tristique fusce congue diam id ornare imperdiet sapien urna');
insert into todo_item (text) values ('cursus urna ut tellus nulla ut erat id');
insert into todo_item (text) values ('amet lobortis sapien sapien non mi integer ac neque');
insert into todo_item (text) values ('nam nulla integer pede justo lacinia eget tincidunt eget tempus');
insert into todo_item (text) values ('in est risus auctor sed tristique in');
insert into todo_item (text) values ('elit sodales scelerisque mauris sit amet eros suspendisse');
insert into todo_item (text) values ('rutrum neque aenean auctor gravida sem praesent id');
insert into todo_item (text) values ('ut at dolor quis odio consequat varius integer ac leo');
insert into todo_item (text) values ('libero nam dui proin');
insert into todo_item (text) values ('eu tincidunt in leo maecenas pulvinar');
insert into todo_item (text) values ('amet sem fusce consequat');
insert into todo_item (text) values ('ipsum primis in faucibus orci luctus et');
insert into todo_item (text) values ('suscipit a feugiat et eros');
insert into todo_item (text) values ('eget orci vehicula condimentum curabitur in libero ut');
insert into todo_item (text) values ('quam nec dui luctus');
insert into todo_item (text) values ('eu interdum eu tincidunt in leo maecenas pulvinar lobortis est');
insert into todo_item (text) values ('nulla tellus in sagittis dui vel');
insert into todo_item (text) values ('pede justo eu massa donec dapibus');
insert into todo_item (text) values ('purus eu magna vulputate luctus cum sociis natoque penatibus');
insert into todo_item (text) values ('ante vivamus tortor duis mattis egestas metus');
insert into todo_item (text) values ('nullam sit amet turpis elementum ligula vehicula consequat morbi');
insert into todo_item (text) values ('ut odio cras mi pede malesuada in imperdiet et');
insert into todo_item (text) values ('nibh in hac habitasse');
insert into todo_item (text) values ('neque duis bibendum morbi non quam nec dui luctus');
insert into todo_item (text) values ('rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel');
insert into todo_item (text) values ('vestibulum rutrum rutrum neque aenean auctor');
insert into todo_item (text) values ('tellus nulla ut erat id mauris vulputate elementum');
insert into todo_item (text) values ('duis consequat dui nec nisi volutpat eleifend donec');
insert into todo_item (text) values ('maecenas rhoncus aliquam lacus morbi quis tortor');
insert into todo_item (text) values ('quisque erat eros viverra');
insert into todo_item (text) values ('imperdiet et commodo vulputate justo');
insert into todo_item (text) values ('consequat morbi a ipsum integer a nibh in quis justo');
insert into todo_item (text) values ('auctor sed tristique in tempus sit amet sem fusce');
insert into todo_item (text) values ('ultrices erat tortor sollicitudin mi sit amet');
insert into todo_item (text) values ('nunc commodo placerat praesent');
insert into todo_item (text) values ('varius nulla facilisi cras non velit');
insert into todo_item (text) values ('magna vestibulum aliquet ultrices');
insert into todo_item (text) values ('nulla sed vel enim sit');
insert into todo_item (text) values ('dapibus at diam nam tristique');
insert into todo_item (text) values ('lacus purus aliquet at feugiat non pretium quis lectus');
insert into todo_item (text) values ('nisi venenatis tristique fusce congue diam id ornare');
insert into todo_item (text) values ('tempor convallis nulla neque libero convallis eget eleifend luctus ultricies');
insert into todo_item (text) values ('neque libero convallis eget eleifend');
insert into todo_item (text) values ('lectus in quam fringilla rhoncus');
insert into todo_item (text) values ('diam neque vestibulum eget vulputate ut');
insert into todo_item (text) values ('integer a nibh in quis justo maecenas rhoncus aliquam lacus');
insert into todo_item (text) values ('blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing');
insert into todo_item (text) values ('turpis elementum ligula vehicula consequat morbi a ipsum integer a');
insert into todo_item (text) values ('lacus morbi sem mauris laoreet ut');
insert into todo_item (text) values ('aliquam erat volutpat in congue etiam justo etiam pretium');
insert into todo_item (text) values ('diam erat fermentum justo nec condimentum neque sapien');
insert into todo_item (text) values ('eros suspendisse accumsan tortor quis turpis');
insert into todo_item (text) values ('sagittis sapien cum sociis natoque penatibus et magnis dis parturient');
insert into todo_item (text) values ('mi pede malesuada in imperdiet');
insert into todo_item (text) values ('mi integer ac neque duis bibendum morbi non quam nec');
insert into todo_item (text) values ('iaculis justo in hac habitasse platea dictumst etiam faucibus');
insert into todo_item (text) values ('viverra diam vitae quam');
insert into todo_item (text) values ('velit id pretium iaculis diam erat fermentum justo nec condimentum');
insert into todo_item (text) values ('magna bibendum imperdiet nullam');
insert into todo_item (text) values ('vivamus vestibulum sagittis sapien cum sociis natoque penatibus et');
insert into todo_item (text) values ('eu est congue elementum');
insert into todo_item (text) values ('suspendisse potenti nullam porttitor lacus at turpis');
insert into todo_item (text) values ('odio donec vitae nisi nam ultrices libero non mattis pulvinar');
insert into todo_item (text) values ('in tempor turpis nec euismod scelerisque quam turpis adipiscing');
insert into todo_item (text) values ('nulla tempus vivamus in felis eu sapien');
insert into todo_item (text) values ('purus phasellus in felis donec semper sapien');
insert into todo_item (text) values ('ut at dolor quis');
insert into todo_item (text) values ('vitae quam suspendisse potenti');
insert into todo_item (text) values ('vulputate elementum nullam varius');
insert into todo_item (text) values ('convallis nulla neque libero convallis eget eleifend luctus ultricies eu');
insert into todo_item (text) values ('ipsum primis in faucibus orci luctus et ultrices posuere');
insert into todo_item (text) values ('vestibulum sagittis sapien cum sociis natoque penatibus et magnis');
insert into todo_item (text) values ('lobortis est phasellus sit amet erat nulla');
insert into todo_item (text) values ('in quis justo maecenas rhoncus aliquam lacus');
insert into todo_item (text) values ('pulvinar nulla pede ullamcorper augue');
insert into todo_item (text) values ('magna ac consequat metus');
insert into todo_item (text) values ('dictumst morbi vestibulum velit id pretium iaculis');
insert into todo_item (text) values ('erat tortor sollicitudin mi sit');
insert into todo_item (text) values ('odio curabitur convallis duis consequat dui nec nisi');
insert into todo_item (text) values ('augue luctus tincidunt nulla mollis molestie lorem');
insert into todo_item (text) values ('ipsum aliquam non mauris morbi non lectus');
insert into todo_item (text) values ('vestibulum rutrum rutrum neque aenean');
insert into todo_item (text) values ('id nisl venenatis lacinia aenean');
insert into todo_item (text) values ('accumsan tortor quis turpis sed ante vivamus tortor duis mattis');
insert into todo_item (text) values ('montes nascetur ridiculus mus etiam vel augue vestibulum rutrum');
insert into todo_item (text) values ('justo in blandit ultrices enim lorem ipsum dolor sit');
insert into todo_item (text) values ('at velit vivamus vel nulla eget eros elementum pellentesque quisque');
insert into todo_item (text) values ('posuere cubilia curae duis faucibus accumsan odio curabitur convallis');
insert into todo_item (text) values ('nulla ut erat id mauris vulputate elementum nullam');
insert into todo_item (text) values ('aliquet massa id lobortis convallis tortor risus dapibus augue');
insert into todo_item (text) values ('magna ac consequat metus sapien ut nunc vestibulum');
insert into todo_item (text) values ('condimentum id luctus nec molestie sed justo');
insert into todo_item (text) values ('aenean sit amet justo morbi ut odio cras');
insert into todo_item (text) values ('massa id lobortis convallis tortor risus');
insert into todo_item (text) values ('penatibus et magnis dis parturient montes nascetur ridiculus mus etiam');
insert into todo_item (text) values ('cubilia curae nulla dapibus dolor vel est');
insert into todo_item (text) values ('sagittis sapien cum sociis natoque penatibus et magnis dis');
insert into todo_item (text) values ('id ligula suspendisse ornare consequat');
insert into todo_item (text) values ('justo maecenas rhoncus aliquam lacus');
insert into todo_item (text) values ('rutrum nulla nunc purus phasellus in felis');
insert into todo_item (text) values ('sem fusce consequat nulla');
insert into todo_item (text) values ('vestibulum sed magna at nunc commodo placerat praesent blandit nam');
insert into todo_item (text) values ('mi integer ac neque duis bibendum');
insert into todo_item (text) values ('aliquet at feugiat non pretium quis lectus suspendisse potenti');
insert into todo_item (text) values ('malesuada in imperdiet et commodo');
insert into todo_item (text) values ('vitae consectetuer eget rutrum at lorem integer tincidunt ante vel');
insert into todo_item (text) values ('morbi ut odio cras mi pede');
insert into todo_item (text) values ('urna pretium nisl ut volutpat sapien');
insert into todo_item (text) values ('hac habitasse platea dictumst maecenas ut massa');
insert into todo_item (text) values ('leo odio porttitor id consequat in');
insert into todo_item (text) values ('duis at velit eu est');
insert into todo_item (text) values ('at turpis donec posuere metus');
insert into todo_item (text) values ('dolor morbi vel lectus in quam fringilla rhoncus mauris');
insert into todo_item (text) values ('quis lectus suspendisse potenti in eleifend quam a odio in');
insert into todo_item (text) values ('sed nisl nunc rhoncus');
insert into todo_item (text) values ('sem duis aliquam convallis');
insert into todo_item (text) values ('justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla');
insert into todo_item (text) values ('amet turpis elementum ligula vehicula consequat morbi a ipsum');
insert into todo_item (text) values ('sapien a libero nam dui proin leo odio porttitor');
insert into todo_item (text) values ('nulla nunc purus phasellus');
insert into todo_item (text) values ('nisi venenatis tristique fusce congue diam id ornare imperdiet sapien');
insert into todo_item (text) values ('ultrices posuere cubilia curae duis faucibus');
insert into todo_item (text) values ('turpis donec posuere metus');
insert into todo_item (text) values ('non velit donec diam neque vestibulum');
insert into todo_item (text) values ('ante ipsum primis in');
insert into todo_item (text) values ('consectetuer adipiscing elit proin risus praesent lectus vestibulum');
insert into todo_item (text) values ('mi in porttitor pede justo eu');
insert into todo_item (text) values ('platea dictumst etiam faucibus cursus');
insert into todo_item (text) values ('pellentesque eget nunc donec quis orci eget orci vehicula condimentum');
insert into todo_item (text) values ('nonummy integer non velit donec diam neque vestibulum eget vulputate');
insert into todo_item (text) values ('amet nulla quisque arcu libero rutrum ac');
insert into todo_item (text) values ('mauris eget massa tempor convallis nulla neque libero');
insert into todo_item (text) values ('sit amet nulla quisque arcu');
insert into todo_item (text) values ('quisque porta volutpat erat quisque erat eros viverra');
insert into todo_item (text) values ('porttitor id consequat in consequat ut nulla sed');
insert into todo_item (text) values ('massa volutpat convallis morbi odio odio elementum eu interdum');
insert into todo_item (text) values ('platea dictumst morbi vestibulum velit id');
insert into todo_item (text) values ('molestie lorem quisque ut erat curabitur gravida nisi');
insert into todo_item (text) values ('libero convallis eget eleifend luctus ultricies eu nibh quisque id');
insert into todo_item (text) values ('arcu sed augue aliquam erat volutpat in congue');
insert into todo_item (text) values ('curae duis faucibus accumsan');
insert into todo_item (text) values ('ultrices posuere cubilia curae');
insert into todo_item (text) values ('auctor sed tristique in');
insert into todo_item (text) values ('natoque penatibus et magnis');
insert into todo_item (text) values ('orci luctus et ultrices');
insert into todo_item (text) values ('nisi vulputate nonummy maecenas tincidunt lacus at');
insert into todo_item (text) values ('non sodales sed tincidunt eu felis');
insert into todo_item (text) values ('accumsan tortor quis turpis sed ante vivamus');
insert into todo_item (text) values ('platea dictumst maecenas ut massa');
insert into todo_item (text) values ('magna ac consequat metus sapien ut nunc');
insert into todo_item (text) values ('at turpis a pede posuere nonummy integer non velit donec');
insert into todo_item (text) values ('a libero nam dui proin leo');
insert into todo_item (text) values ('velit nec nisi vulputate nonummy maecenas');
insert into todo_item (text) values ('sapien cum sociis natoque penatibus et');
insert into todo_item (text) values ('non interdum in ante');
insert into todo_item (text) values ('vitae ipsum aliquam non');
insert into todo_item (text) values ('rutrum at lorem integer tincidunt ante vel ipsum praesent blandit');
insert into todo_item (text) values ('pellentesque quisque porta volutpat erat');
insert into todo_item (text) values ('nisl ut volutpat sapien arcu sed augue aliquam');
insert into todo_item (text) values ('rutrum nulla tellus in sagittis dui');
insert into todo_item (text) values ('a suscipit nulla elit');
insert into todo_item (text) values ('mauris enim leo rhoncus');
insert into todo_item (text) values ('malesuada in imperdiet et commodo vulputate justo in blandit ultrices');
insert into todo_item (text) values ('nulla pede ullamcorper augue a suscipit nulla');
insert into todo_item (text) values ('id lobortis convallis tortor risus dapibus');
insert into todo_item (text) values ('morbi ut odio cras mi pede malesuada');
insert into todo_item (text) values ('volutpat eleifend donec ut dolor morbi vel');
insert into todo_item (text) values ('pede malesuada in imperdiet et commodo vulputate justo in');
insert into todo_item (text) values ('vehicula condimentum curabitur in libero ut massa volutpat convallis');
insert into todo_item (text) values ('non ligula pellentesque ultrices phasellus id sapien');
insert into todo_item (text) values ('mauris eget massa tempor');
insert into todo_item (text) values ('nisl nunc nisl duis bibendum');
insert into todo_item (text) values ('mi in porttitor pede justo eu massa donec dapibus');
insert into todo_item (text) values ('parturient montes nascetur ridiculus mus etiam vel augue vestibulum');
insert into todo_item (text) values ('ullamcorper purus sit amet nulla quisque arcu libero rutrum ac');
insert into todo_item (text) values ('urna ut tellus nulla ut erat id mauris vulputate elementum');
insert into todo_item (text) values ('magna ac consequat metus sapien ut nunc vestibulum ante');
insert into todo_item (text) values ('nulla suspendisse potenti cras in purus eu magna vulputate luctus');
insert into todo_item (text) values ('est et tempus semper est quam pharetra magna ac consequat');
insert into todo_item (text) values ('nam dui proin leo odio porttitor id consequat in');
insert into todo_item (text) values ('semper sapien a libero nam dui proin leo');
insert into todo_item (text) values ('cum sociis natoque penatibus et');
insert into todo_item (text) values ('consequat morbi a ipsum integer a nibh in');
insert into todo_item (text) values ('iaculis justo in hac habitasse platea dictumst etiam faucibus');
insert into todo_item (text) values ('suspendisse potenti cras in purus eu magna vulputate');
insert into todo_item (text) values ('vivamus vestibulum sagittis sapien cum sociis');
insert into todo_item (text) values ('ligula sit amet eleifend pede libero quis orci');
insert into todo_item (text) values ('ut odio cras mi pede malesuada');
insert into todo_item (text) values ('blandit lacinia erat vestibulum sed');
insert into todo_item (text) values ('vehicula condimentum curabitur in');
insert into todo_item (text) values ('tortor sollicitudin mi sit amet lobortis sapien sapien non');
insert into todo_item (text) values ('congue risus semper porta volutpat quam pede lobortis');
insert into todo_item (text) values ('posuere cubilia curae mauris viverra diam vitae quam suspendisse');
insert into todo_item (text) values ('lacinia sapien quis libero nullam sit amet');
insert into todo_item (text) values ('ligula nec sem duis aliquam convallis nunc');
insert into todo_item (text) values ('eu nibh quisque id justo sit amet sapien');
insert into todo_item (text) values ('consequat morbi a ipsum integer');
insert into todo_item (text) values ('ligula in lacus curabitur at');
insert into todo_item (text) values ('luctus et ultrices posuere cubilia curae duis faucibus accumsan odio');
insert into todo_item (text) values ('nibh fusce lacus purus aliquet at feugiat non pretium quis');
insert into todo_item (text) values ('cursus id turpis integer aliquet massa');
insert into todo_item (text) values ('vestibulum sit amet cursus id turpis integer aliquet');
insert into todo_item (text) values ('odio odio elementum eu interdum eu tincidunt in');
insert into todo_item (text) values ('pharetra magna ac consequat metus sapien ut nunc');
insert into todo_item (text) values ('sollicitudin vitae consectetuer eget rutrum at lorem integer');
insert into todo_item (text) values ('magna at nunc commodo');
insert into todo_item (text) values ('lacus curabitur at ipsum ac tellus');
insert into todo_item (text) values ('neque sapien placerat ante nulla justo aliquam quis turpis eget');
insert into todo_item (text) values ('risus semper porta volutpat quam pede lobortis ligula');
insert into todo_item (text) values ('aenean lectus pellentesque eget nunc donec');
insert into todo_item (text) values ('habitasse platea dictumst etiam faucibus cursus urna ut tellus');
insert into todo_item (text) values ('bibendum felis sed interdum venenatis turpis enim');
insert into todo_item (text) values ('et commodo vulputate justo');
insert into todo_item (text) values ('integer pede justo lacinia eget tincidunt');
insert into todo_item (text) values ('metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean');
insert into todo_item (text) values ('sapien sapien non mi integer ac neque duis bibendum morbi');
insert into todo_item (text) values ('in quam fringilla rhoncus mauris enim leo rhoncus');
insert into todo_item (text) values ('proin interdum mauris non ligula pellentesque ultrices phasellus id');
insert into todo_item (text) values ('amet lobortis sapien sapien non');
insert into todo_item (text) values ('massa tempor convallis nulla neque libero convallis');
insert into todo_item (text) values ('maecenas pulvinar lobortis est phasellus');
insert into todo_item (text) values ('diam id ornare imperdiet');
insert into todo_item (text) values ('primis in faucibus orci luctus');
insert into todo_item (text) values ('aenean sit amet justo morbi');
insert into todo_item (text) values ('accumsan odio curabitur convallis duis consequat dui');
insert into todo_item (text) values ('eleifend quam a odio in hac habitasse platea');
insert into todo_item (text) values ('proin at turpis a pede posuere nonummy');
insert into todo_item (text) values ('commodo vulputate justo in blandit ultrices enim lorem');
insert into todo_item (text) values ('sollicitudin mi sit amet lobortis sapien');
insert into todo_item (text) values ('vestibulum sit amet cursus id');
insert into todo_item (text) values ('erat id mauris vulputate elementum nullam');
insert into todo_item (text) values ('nascetur ridiculus mus etiam vel augue vestibulum rutrum');
insert into todo_item (text) values ('non quam nec dui luctus rutrum nulla tellus in');
insert into todo_item (text) values ('odio donec vitae nisi nam ultrices libero non mattis');
insert into todo_item (text) values ('accumsan odio curabitur convallis duis consequat dui nec nisi');
insert into todo_item (text) values ('montes nascetur ridiculus mus etiam vel augue vestibulum rutrum');
insert into todo_item (text) values ('erat eros viverra eget');
insert into todo_item (text) values ('at turpis donec posuere metus vitae ipsum aliquam non mauris');
insert into todo_item (text) values ('vel nisl duis ac nibh fusce');
insert into todo_item (text) values ('curabitur in libero ut massa volutpat');
insert into todo_item (text) values ('vulputate ut ultrices vel');
insert into todo_item (text) values ('eget vulputate ut ultrices vel augue vestibulum');
insert into todo_item (text) values ('nisi nam ultrices libero');
insert into todo_item (text) values ('aliquam augue quam sollicitudin vitae consectetuer');
insert into todo_item (text) values ('amet eros suspendisse accumsan tortor quis');
insert into todo_item (text) values ('hac habitasse platea dictumst');
insert into todo_item (text) values ('arcu sed augue aliquam erat volutpat in');
insert into todo_item (text) values ('sapien placerat ante nulla justo aliquam quis turpis eget elit');
insert into todo_item (text) values ('turpis adipiscing lorem vitae mattis nibh ligula nec');
insert into todo_item (text) values ('diam erat fermentum justo nec condimentum neque sapien placerat ante');
insert into todo_item (text) values ('ac enim in tempor turpis nec');
insert into todo_item (text) values ('tempus vivamus in felis eu sapien cursus vestibulum proin');
insert into todo_item (text) values ('porttitor lorem id ligula');
insert into todo_item (text) values ('leo odio condimentum id luctus nec molestie sed justo pellentesque');
insert into todo_item (text) values ('augue aliquam erat volutpat in');
insert into todo_item (text) values ('consequat nulla nisl nunc nisl duis');
insert into todo_item (text) values ('congue eget semper rutrum nulla nunc purus phasellus');
insert into todo_item (text) values ('sed justo pellentesque viverra pede');
insert into todo_item (text) values ('leo maecenas pulvinar lobortis est');
insert into todo_item (text) values ('quisque ut erat curabitur gravida nisi at nibh in hac');
insert into todo_item (text) values ('in sagittis dui vel nisl duis ac');
insert into todo_item (text) values ('id nulla ultrices aliquet maecenas leo odio');
insert into todo_item (text) values ('penatibus et magnis dis parturient');
insert into todo_item (text) values ('interdum venenatis turpis enim blandit mi in porttitor pede justo');
insert into todo_item (text) values ('ac est lacinia nisi venenatis tristique fusce congue');
insert into todo_item (text) values ('gravida sem praesent id massa id nisl venenatis lacinia');
insert into todo_item (text) values ('massa id nisl venenatis lacinia aenean sit');
insert into todo_item (text) values ('congue etiam justo etiam');
insert into todo_item (text) values ('dis parturient montes nascetur');
insert into todo_item (text) values ('lacus purus aliquet at feugiat non pretium');
insert into todo_item (text) values ('nisl nunc nisl duis bibendum felis sed interdum venenatis turpis');
insert into todo_item (text) values ('enim blandit mi in');
insert into todo_item (text) values ('proin risus praesent lectus vestibulum quam sapien varius ut blandit');
insert into todo_item (text) values ('mi nulla ac enim in tempor turpis nec euismod');
insert into todo_item (text) values ('augue aliquam erat volutpat in congue');
insert into todo_item (text) values ('ornare consequat lectus in est risus auctor sed tristique');
insert into todo_item (text) values ('nunc rhoncus dui vel');
insert into todo_item (text) values ('nulla suspendisse potenti cras in');
insert into todo_item (text) values ('sodales sed tincidunt eu felis');
insert into todo_item (text) values ('at velit eu est congue elementum in hac habitasse platea');
insert into todo_item (text) values ('felis fusce posuere felis sed lacus morbi sem mauris laoreet');
insert into todo_item (text) values ('non pretium quis lectus suspendisse');
insert into todo_item (text) values ('sit amet sapien dignissim vestibulum vestibulum');
insert into todo_item (text) values ('natoque penatibus et magnis dis parturient montes');
insert into todo_item (text) values ('id massa id nisl');
insert into todo_item (text) values ('id massa id nisl venenatis lacinia aenean sit amet');
insert into todo_item (text) values ('sapien quis libero nullam');
insert into todo_item (text) values ('dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at');
insert into todo_item (text) values ('augue luctus tincidunt nulla');
insert into todo_item (text) values ('cubilia curae mauris viverra diam vitae quam suspendisse');
insert into todo_item (text) values ('faucibus orci luctus et ultrices posuere');
insert into todo_item (text) values ('cras in purus eu');
insert into todo_item (text) values ('nisl nunc rhoncus dui');
insert into todo_item (text) values ('nulla integer pede justo lacinia eget tincidunt');
insert into todo_item (text) values ('turpis sed ante vivamus tortor duis');
insert into todo_item (text) values ('libero non mattis pulvinar nulla pede ullamcorper augue');
insert into todo_item (text) values ('vivamus metus arcu adipiscing molestie hendrerit at');
insert into todo_item (text) values ('ut tellus nulla ut erat id mauris vulputate');
insert into todo_item (text) values ('dolor sit amet consectetuer');
insert into todo_item (text) values ('sapien a libero nam dui proin leo');
insert into todo_item (text) values ('imperdiet et commodo vulputate justo in blandit ultrices');
insert into todo_item (text) values ('est risus auctor sed tristique in tempus sit');
insert into todo_item (text) values ('tellus semper interdum mauris ullamcorper purus sit amet nulla quisque');
insert into todo_item (text) values ('integer aliquet massa id lobortis');
insert into todo_item (text) values ('ut at dolor quis odio consequat varius');
insert into todo_item (text) values ('volutpat in congue etiam justo etiam');
insert into todo_item (text) values ('dui maecenas tristique est et tempus semper est quam');
insert into todo_item (text) values ('platea dictumst morbi vestibulum velit id pretium');
insert into todo_item (text) values ('duis mattis egestas metus aenean fermentum donec ut mauris');
insert into todo_item (text) values ('augue aliquam erat volutpat in congue etiam justo etiam pretium');
insert into todo_item (text) values ('nullam sit amet turpis');
insert into todo_item (text) values ('potenti in eleifend quam a odio in hac habitasse');
insert into todo_item (text) values ('velit vivamus vel nulla eget');
insert into todo_item (text) values ('molestie sed justo pellentesque');
insert into todo_item (text) values ('aliquam convallis nunc proin at turpis a pede posuere nonummy');
insert into todo_item (text) values ('nullam molestie nibh in lectus');
insert into todo_item (text) values ('vestibulum ante ipsum primis in faucibus orci');
insert into todo_item (text) values ('pellentesque at nulla suspendisse potenti cras');
insert into todo_item (text) values ('vel dapibus at diam nam tristique tortor eu pede');
insert into todo_item (text) values ('erat curabitur gravida nisi at nibh in hac');
insert into todo_item (text) values ('sapien varius ut blandit non interdum in');
insert into todo_item (text) values ('id ligula suspendisse ornare consequat lectus in est');
insert into todo_item (text) values ('nunc viverra dapibus nulla suscipit ligula in lacus curabitur');
insert into todo_item (text) values ('id nulla ultrices aliquet maecenas leo odio condimentum');
insert into todo_item (text) values ('sed lacus morbi sem');
insert into todo_item (text) values ('aenean fermentum donec ut mauris eget massa tempor convallis');
insert into todo_item (text) values ('duis faucibus accumsan odio curabitur convallis');
insert into todo_item (text) values ('mauris laoreet ut rhoncus aliquet');
insert into todo_item (text) values ('et magnis dis parturient montes nascetur');
insert into todo_item (text) values ('sagittis nam congue risus semper porta volutpat quam pede lobortis');
insert into todo_item (text) values ('vel accumsan tellus nisi eu orci mauris');
insert into todo_item (text) values ('aenean auctor gravida sem praesent');
insert into todo_item (text) values ('nulla tellus in sagittis');
insert into todo_item (text) values ('aenean fermentum donec ut mauris eget massa tempor convallis nulla');
insert into todo_item (text) values ('eros vestibulum ac est lacinia nisi venenatis tristique fusce');
insert into todo_item (text) values ('suspendisse ornare consequat lectus in est risus auctor');
insert into todo_item (text) values ('mauris morbi non lectus aliquam');
insert into todo_item (text) values ('maecenas ut massa quis augue luctus tincidunt nulla mollis molestie');
insert into todo_item (text) values ('ut at dolor quis odio consequat varius integer ac');
insert into todo_item (text) values ('tempus vivamus in felis eu sapien cursus vestibulum proin');
insert into todo_item (text) values ('enim leo rhoncus sed vestibulum sit amet cursus id');
insert into todo_item (text) values ('habitasse platea dictumst aliquam augue');
insert into todo_item (text) values ('ut blandit non interdum in ante vestibulum ante');
insert into todo_item (text) values ('lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet');
insert into todo_item (text) values ('maecenas tincidunt lacus at');
insert into todo_item (text) values ('augue luctus tincidunt nulla mollis molestie lorem quisque ut');
insert into todo_item (text) values ('ipsum praesent blandit lacinia erat vestibulum');
insert into todo_item (text) values ('viverra eget congue eget semper rutrum nulla nunc purus');
insert into todo_item (text) values ('justo nec condimentum neque');
insert into todo_item (text) values ('in tempus sit amet sem fusce');
insert into todo_item (text) values ('convallis duis consequat dui nec nisi volutpat eleifend donec ut');
insert into todo_item (text) values ('odio odio elementum eu interdum eu tincidunt');
insert into todo_item (text) values ('sit amet nunc viverra dapibus nulla suscipit ligula');
insert into todo_item (text) values ('ut odio cras mi pede');
insert into todo_item (text) values ('vitae ipsum aliquam non');
insert into todo_item (text) values ('id justo sit amet sapien dignissim vestibulum vestibulum ante');
insert into todo_item (text) values ('nascetur ridiculus mus etiam vel augue vestibulum rutrum');
insert into todo_item (text) values ('enim in tempor turpis nec euismod scelerisque quam turpis');
insert into todo_item (text) values ('fermentum justo nec condimentum neque sapien placerat ante nulla');
insert into todo_item (text) values ('luctus et ultrices posuere cubilia curae donec pharetra');
insert into todo_item (text) values ('mauris enim leo rhoncus sed vestibulum sit');
insert into todo_item (text) values ('dolor sit amet consectetuer adipiscing elit proin risus');
insert into todo_item (text) values ('pellentesque ultrices phasellus id');
insert into todo_item (text) values ('arcu sed augue aliquam erat volutpat');
insert into todo_item (text) values ('etiam justo etiam pretium iaculis justo in');
insert into todo_item (text) values ('enim lorem ipsum dolor sit amet consectetuer adipiscing');
insert into todo_item (text) values ('integer tincidunt ante vel ipsum praesent blandit lacinia');
insert into todo_item (text) values ('montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum');
insert into todo_item (text) values ('eu sapien cursus vestibulum proin eu mi nulla ac enim');
insert into todo_item (text) values ('rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus');
insert into todo_item (text) values ('aenean sit amet justo morbi ut odio cras mi');
insert into todo_item (text) values ('adipiscing molestie hendrerit at vulputate vitae nisl aenean');
insert into todo_item (text) values ('luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur');
insert into todo_item (text) values ('in purus eu magna vulputate luctus');
insert into todo_item (text) values ('sit amet justo morbi');
insert into todo_item (text) values ('elementum pellentesque quisque porta volutpat erat quisque');
insert into todo_item (text) values ('in congue etiam justo etiam pretium iaculis');
insert into todo_item (text) values ('enim sit amet nunc viverra dapibus');
insert into todo_item (text) values ('quis tortor id nulla ultrices');
insert into todo_item (text) values ('enim blandit mi in');
insert into todo_item (text) values ('erat volutpat in congue etiam justo etiam pretium iaculis');
insert into todo_item (text) values ('ut tellus nulla ut erat id mauris vulputate');
insert into todo_item (text) values ('sit amet justo morbi ut');
insert into todo_item (text) values ('semper est quam pharetra');
insert into todo_item (text) values ('orci luctus et ultrices posuere');
insert into todo_item (text) values ('leo pellentesque ultrices mattis odio donec vitae nisi nam');
insert into todo_item (text) values ('proin at turpis a pede posuere nonummy');
insert into todo_item (text) values ('fusce posuere felis sed lacus morbi sem mauris laoreet');
insert into todo_item (text) values ('nulla quisque arcu libero');
insert into todo_item (text) values ('eu magna vulputate luctus cum');
insert into todo_item (text) values ('libero ut massa volutpat convallis morbi odio odio elementum eu');
insert into todo_item (text) values ('ac consequat metus sapien');
insert into todo_item (text) values ('phasellus id sapien in sapien iaculis');
insert into todo_item (text) values ('ut erat curabitur gravida nisi at nibh in');
insert into todo_item (text) values ('est et tempus semper est quam pharetra magna');
insert into todo_item (text) values ('quis turpis sed ante vivamus tortor duis');
insert into todo_item (text) values ('volutpat in congue etiam justo etiam');
insert into todo_item (text) values ('nibh ligula nec sem duis aliquam convallis');
insert into todo_item (text) values ('nulla tempus vivamus in felis eu sapien cursus');
insert into todo_item (text) values ('nulla nunc purus phasellus in felis donec semper sapien');
insert into todo_item (text) values ('nullam molestie nibh in');
insert into todo_item (text) values ('vulputate nonummy maecenas tincidunt lacus at');
insert into todo_item (text) values ('eget nunc donec quis orci eget orci vehicula condimentum');
insert into todo_item (text) values ('enim leo rhoncus sed vestibulum sit amet cursus id turpis');
insert into todo_item (text) values ('tortor risus dapibus augue vel accumsan tellus');
insert into todo_item (text) values ('sapien non mi integer ac neque duis bibendum morbi non');
insert into todo_item (text) values ('non sodales sed tincidunt eu felis fusce posuere felis');
insert into todo_item (text) values ('lacus purus aliquet at feugiat');
insert into todo_item (text) values ('pretium iaculis diam erat fermentum justo nec condimentum neque sapien');
insert into todo_item (text) values ('nisl aenean lectus pellentesque eget nunc donec quis orci eget');
insert into todo_item (text) values ('ipsum primis in faucibus orci');
insert into todo_item (text) values ('ligula pellentesque ultrices phasellus id sapien');
insert into todo_item (text) values ('turpis enim blandit mi in porttitor pede justo eu massa');
insert into todo_item (text) values ('quam pharetra magna ac consequat metus sapien');
insert into todo_item (text) values ('platea dictumst morbi vestibulum velit');
insert into todo_item (text) values ('lacus curabitur at ipsum ac tellus semper interdum');
insert into todo_item (text) values ('amet justo morbi ut');
insert into todo_item (text) values ('ut mauris eget massa tempor convallis nulla neque libero');
insert into todo_item (text) values ('eget eleifend luctus ultricies eu');
insert into todo_item (text) values ('nullam molestie nibh in lectus pellentesque at nulla');
insert into todo_item (text) values ('elementum eu interdum eu tincidunt');
insert into todo_item (text) values ('tempus sit amet sem');
insert into todo_item (text) values ('posuere felis sed lacus morbi sem');
insert into todo_item (text) values ('integer ac neque duis bibendum morbi non');
insert into todo_item (text) values ('ipsum integer a nibh in quis justo');
insert into todo_item (text) values ('ornare imperdiet sapien urna pretium nisl ut volutpat sapien');
insert into todo_item (text) values ('est quam pharetra magna ac consequat metus sapien ut nunc');
insert into todo_item (text) values ('et ultrices posuere cubilia curae mauris');
insert into todo_item (text) values ('at ipsum ac tellus semper');
insert into todo_item (text) values ('justo sit amet sapien');
insert into todo_item (text) values ('nulla neque libero convallis');
insert into todo_item (text) values ('tellus nisi eu orci');
insert into todo_item (text) values ('semper interdum mauris ullamcorper purus sit amet');
insert into todo_item (text) values ('convallis nunc proin at turpis a pede posuere nonummy integer');
insert into todo_item (text) values ('pellentesque viverra pede ac diam cras pellentesque volutpat');
insert into todo_item (text) values ('porta volutpat quam pede lobortis ligula');
insert into todo_item (text) values ('quam nec dui luctus rutrum nulla tellus in sagittis dui');
insert into todo_item (text) values ('in faucibus orci luctus et ultrices posuere cubilia');
insert into todo_item (text) values ('curae donec pharetra magna vestibulum');
insert into todo_item (text) values ('scelerisque quam turpis adipiscing lorem vitae');
insert into todo_item (text) values ('eu est congue elementum in hac habitasse');
insert into todo_item (text) values ('malesuada in imperdiet et commodo vulputate justo in blandit ultrices');
insert into todo_item (text) values ('nullam orci pede venenatis non sodales sed tincidunt eu felis');
insert into todo_item (text) values ('congue etiam justo etiam pretium iaculis justo in hac habitasse');
insert into todo_item (text) values ('nam nulla integer pede justo lacinia eget tincidunt');
insert into todo_item (text) values ('ac est lacinia nisi venenatis');
insert into todo_item (text) values ('habitasse platea dictumst aliquam augue');
insert into todo_item (text) values ('pede morbi porttitor lorem id ligula suspendisse ornare');
insert into todo_item (text) values ('nulla elit ac nulla sed');
insert into todo_item (text) values ('aliquet maecenas leo odio condimentum');
insert into todo_item (text) values ('donec odio justo sollicitudin');
insert into todo_item (text) values ('aenean lectus pellentesque eget nunc donec quis orci eget orci');
insert into todo_item (text) values ('lacus at velit vivamus vel nulla eget');
insert into todo_item (text) values ('non mi integer ac');
insert into todo_item (text) values ('blandit lacinia erat vestibulum sed magna at nunc commodo placerat');
insert into todo_item (text) values ('ultrices erat tortor sollicitudin');
insert into todo_item (text) values ('posuere nonummy integer non velit donec diam');
insert into todo_item (text) values ('aenean auctor gravida sem praesent id massa');
insert into todo_item (text) values ('posuere cubilia curae nulla dapibus dolor vel est');
insert into todo_item (text) values ('non mauris morbi non lectus aliquam sit amet');
insert into todo_item (text) values ('ridiculus mus etiam vel augue vestibulum rutrum rutrum neque');
insert into todo_item (text) values ('phasellus sit amet erat nulla tempus vivamus in');
insert into todo_item (text) values ('dapibus at diam nam tristique tortor');
insert into todo_item (text) values ('lectus pellentesque eget nunc donec quis');
insert into todo_item (text) values ('et ultrices posuere cubilia curae nulla dapibus');
insert into todo_item (text) values ('fermentum justo nec condimentum neque sapien placerat');
insert into todo_item (text) values ('orci pede venenatis non sodales sed tincidunt eu');
insert into todo_item (text) values ('lacinia sapien quis libero nullam sit amet turpis elementum');
insert into todo_item (text) values ('odio porttitor id consequat in consequat ut nulla');
insert into todo_item (text) values ('eu tincidunt in leo maecenas pulvinar lobortis est');
insert into todo_item (text) values ('nulla suscipit ligula in lacus');
insert into todo_item (text) values ('viverra diam vitae quam suspendisse potenti');
insert into todo_item (text) values ('metus arcu adipiscing molestie hendrerit at');
insert into todo_item (text) values ('nec molestie sed justo');
insert into todo_item (text) values ('nulla suspendisse potenti cras in purus eu magna');
insert into todo_item (text) values ('sed magna at nunc commodo placerat praesent');
insert into todo_item (text) values ('nulla elit ac nulla sed vel enim sit amet nunc');
insert into todo_item (text) values ('orci eget orci vehicula condimentum');
insert into todo_item (text) values ('donec semper sapien a libero nam dui');
insert into todo_item (text) values ('ullamcorper purus sit amet nulla');
insert into todo_item (text) values ('pulvinar nulla pede ullamcorper augue');
insert into todo_item (text) values ('mi sit amet lobortis sapien');
insert into todo_item (text) values ('pede lobortis ligula sit amet eleifend pede libero');
insert into todo_item (text) values ('sed nisl nunc rhoncus dui vel');
insert into todo_item (text) values ('dictumst aliquam augue quam sollicitudin vitae consectetuer eget');
insert into todo_item (text) values ('congue diam id ornare imperdiet');
insert into todo_item (text) values ('morbi non lectus aliquam sit amet diam');
insert into todo_item (text) values ('consequat lectus in est risus');
insert into todo_item (text) values ('integer pede justo lacinia eget tincidunt eget');
insert into todo_item (text) values ('mauris laoreet ut rhoncus aliquet pulvinar sed nisl');
insert into todo_item (text) values ('consequat metus sapien ut nunc vestibulum');
insert into todo_item (text) values ('at ipsum ac tellus');
insert into todo_item (text) values ('dapibus duis at velit eu est congue elementum');
insert into todo_item (text) values ('mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit');
insert into todo_item (text) values ('vulputate elementum nullam varius nulla facilisi cras non');
insert into todo_item (text) values ('nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget');
insert into todo_item (text) values ('felis sed lacus morbi sem mauris laoreet ut');
insert into todo_item (text) values ('lacinia erat vestibulum sed magna at');
insert into todo_item (text) values ('nunc purus phasellus in');
insert into todo_item (text) values ('placerat ante nulla justo aliquam quis');
insert into todo_item (text) values ('nibh in lectus pellentesque at nulla suspendisse');
insert into todo_item (text) values ('aliquam convallis nunc proin at turpis a pede posuere');
insert into todo_item (text) values ('amet diam in magna bibendum imperdiet nullam');
insert into todo_item (text) values ('eu magna vulputate luctus cum sociis natoque penatibus et magnis');
insert into todo_item (text) values ('ultricies eu nibh quisque id justo sit amet');
insert into todo_item (text) values ('mi nulla ac enim in tempor turpis');
insert into todo_item (text) values ('in hac habitasse platea');
insert into todo_item (text) values ('odio in hac habitasse platea dictumst');
insert into todo_item (text) values ('massa id nisl venenatis lacinia aenean sit amet justo');
insert into todo_item (text) values ('justo pellentesque viverra pede ac diam');
insert into todo_item (text) values ('maecenas pulvinar lobortis est phasellus sit');
insert into todo_item (text) values ('sed nisl nunc rhoncus');
insert into todo_item (text) values ('dignissim vestibulum vestibulum ante ipsum primis in faucibus');
insert into todo_item (text) values ('vel enim sit amet nunc viverra dapibus nulla');
insert into todo_item (text) values ('duis at velit eu est');
insert into todo_item (text) values ('et eros vestibulum ac est lacinia nisi venenatis tristique fusce');
insert into todo_item (text) values ('metus sapien ut nunc vestibulum ante');
insert into todo_item (text) values ('tincidunt nulla mollis molestie lorem quisque ut');
insert into todo_item (text) values ('eleifend quam a odio in hac habitasse platea dictumst maecenas');
insert into todo_item (text) values ('eget eros elementum pellentesque quisque porta volutpat erat quisque erat');
insert into todo_item (text) values ('nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque');
insert into todo_item (text) values ('in felis donec semper sapien a libero nam dui');
insert into todo_item (text) values ('quis augue luctus tincidunt nulla mollis');
insert into todo_item (text) values ('integer a nibh in quis justo maecenas');
insert into todo_item (text) values ('sit amet eros suspendisse accumsan tortor quis turpis');
insert into todo_item (text) values ('porta volutpat quam pede lobortis');
insert into todo_item (text) values ('sapien placerat ante nulla justo');
insert into todo_item (text) values ('mauris laoreet ut rhoncus');
insert into todo_item (text) values ('at turpis a pede posuere nonummy integer non velit donec');
insert into todo_item (text) values ('placerat praesent blandit nam nulla integer pede justo lacinia');
insert into todo_item (text) values ('ullamcorper purus sit amet nulla');
insert into todo_item (text) values ('quam fringilla rhoncus mauris enim leo rhoncus');
insert into todo_item (text) values ('libero quis orci nullam molestie nibh in lectus pellentesque at');
insert into todo_item (text) values ('felis sed interdum venenatis turpis enim blandit mi');
insert into todo_item (text) values ('aliquet massa id lobortis convallis');
insert into todo_item (text) values ('at nulla suspendisse potenti cras in');
insert into todo_item (text) values ('velit vivamus vel nulla');
insert into todo_item (text) values ('consequat metus sapien ut nunc');
insert into todo_item (text) values ('sollicitudin mi sit amet lobortis sapien sapien non mi integer');
insert into todo_item (text) values ('sem praesent id massa id nisl venenatis lacinia');
insert into todo_item (text) values ('parturient montes nascetur ridiculus mus etiam');
insert into todo_item (text) values ('dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien');
insert into todo_item (text) values ('phasellus sit amet erat nulla tempus vivamus in');
insert into todo_item (text) values ('ligula nec sem duis aliquam convallis nunc proin at');
insert into todo_item (text) values ('vel est donec odio justo sollicitudin ut');
insert into todo_item (text) values ('pretium quis lectus suspendisse potenti in eleifend quam a odio');
insert into todo_item (text) values ('luctus et ultrices posuere cubilia curae duis faucibus accumsan odio');
insert into todo_item (text) values ('est phasellus sit amet');
insert into todo_item (text) values ('morbi vestibulum velit id pretium iaculis diam erat fermentum justo');
insert into todo_item (text) values ('tempus vel pede morbi porttitor lorem id ligula suspendisse');
insert into todo_item (text) values ('viverra dapibus nulla suscipit ligula in lacus curabitur');
insert into todo_item (text) values ('vestibulum ante ipsum primis in faucibus orci');
insert into todo_item (text) values ('arcu sed augue aliquam erat volutpat in');
insert into todo_item (text) values ('posuere felis sed lacus morbi sem mauris laoreet');
insert into todo_item (text) values ('erat quisque erat eros viverra eget congue eget semper rutrum');
insert into todo_item (text) values ('maecenas leo odio condimentum id luctus');
insert into todo_item (text) values ('accumsan felis ut at dolor');
insert into todo_item (text) values ('mauris eget massa tempor convallis');
insert into todo_item (text) values ('ac est lacinia nisi venenatis tristique fusce');
insert into todo_item (text) values ('libero nullam sit amet turpis elementum ligula vehicula');
insert into todo_item (text) values ('amet eros suspendisse accumsan tortor quis turpis sed ante');
insert into todo_item (text) values ('vestibulum ante ipsum primis');
insert into todo_item (text) values ('vitae consectetuer eget rutrum at lorem integer tincidunt');
insert into todo_item (text) values ('libero rutrum ac lobortis vel dapibus at diam');
insert into todo_item (text) values ('nulla nunc purus phasellus in');
insert into todo_item (text) values ('eget tincidunt eget tempus vel pede morbi');
insert into todo_item (text) values ('ligula nec sem duis aliquam convallis');
insert into todo_item (text) values ('mi sit amet lobortis sapien sapien non mi integer ac');
insert into todo_item (text) values ('pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac');
insert into todo_item (text) values ('morbi odio odio elementum eu interdum eu tincidunt in');
insert into todo_item (text) values ('volutpat sapien arcu sed augue aliquam erat volutpat in');
insert into todo_item (text) values ('iaculis diam erat fermentum justo nec condimentum neque sapien');
insert into todo_item (text) values ('nulla facilisi cras non velit nec nisi');
insert into todo_item (text) values ('magna vulputate luctus cum sociis natoque penatibus et magnis');
insert into todo_item (text) values ('ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue');
insert into todo_item (text) values ('volutpat eleifend donec ut dolor morbi vel lectus in quam');
insert into todo_item (text) values ('ut erat id mauris vulputate elementum');
insert into todo_item (text) values ('dapibus nulla suscipit ligula in lacus');
insert into todo_item (text) values ('sed justo pellentesque viverra pede ac diam');
insert into todo_item (text) values ('mauris morbi non lectus aliquam sit amet diam in magna');
insert into todo_item (text) values ('ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue');
insert into todo_item (text) values ('sapien arcu sed augue');
insert into todo_item (text) values ('habitasse platea dictumst aliquam augue quam sollicitudin vitae');
insert into todo_item (text) values ('natoque penatibus et magnis dis parturient montes nascetur ridiculus mus');
insert into todo_item (text) values ('semper est quam pharetra magna ac consequat metus');
insert into todo_item (text) values ('ut tellus nulla ut erat');
insert into todo_item (text) values ('leo pellentesque ultrices mattis odio donec vitae');
insert into todo_item (text) values ('sociis natoque penatibus et magnis dis parturient montes');
insert into todo_item (text) values ('dapibus nulla suscipit ligula');
insert into todo_item (text) values ('pretium iaculis justo in');
insert into todo_item (text) values ('felis ut at dolor quis');
insert into todo_item (text) values ('morbi porttitor lorem id ligula suspendisse ornare consequat lectus');
insert into todo_item (text) values ('dui maecenas tristique est et tempus semper est quam');
insert into todo_item (text) values ('parturient montes nascetur ridiculus');
insert into todo_item (text) values ('nulla sed vel enim sit amet');
insert into todo_item (text) values ('nulla eget eros elementum pellentesque quisque porta volutpat');
insert into todo_item (text) values ('dapibus dolor vel est donec');
insert into todo_item (text) values ('eget orci vehicula condimentum');
insert into todo_item (text) values ('quis tortor id nulla');
insert into todo_item (text) values ('semper interdum mauris ullamcorper purus sit amet nulla quisque arcu');
insert into todo_item (text) values ('id nisl venenatis lacinia aenean sit amet justo morbi ut');
insert into todo_item (text) values ('platea dictumst etiam faucibus cursus urna ut tellus');
insert into todo_item (text) values ('lorem id ligula suspendisse ornare consequat');
insert into todo_item (text) values ('at lorem integer tincidunt ante vel ipsum');
insert into todo_item (text) values ('purus phasellus in felis donec semper sapien a');
insert into todo_item (text) values ('nulla tellus in sagittis dui vel nisl duis ac nibh');
insert into todo_item (text) values ('morbi a ipsum integer a');
insert into todo_item (text) values ('sed justo pellentesque viverra pede ac diam cras pellentesque');
insert into todo_item (text) values ('nibh quisque id justo sit amet sapien dignissim vestibulum');
insert into todo_item (text) values ('nisi vulputate nonummy maecenas');
insert into todo_item (text) values ('ipsum primis in faucibus');
insert into todo_item (text) values ('id massa id nisl venenatis lacinia');
insert into todo_item (text) values ('eget eros elementum pellentesque quisque porta volutpat erat quisque erat');
insert into todo_item (text) values ('mi sit amet lobortis sapien sapien non mi integer');
insert into todo_item (text) values ('pellentesque viverra pede ac diam cras pellentesque');
insert into todo_item (text) values ('dui vel sem sed');
insert into todo_item (text) values ('ligula suspendisse ornare consequat');
insert into todo_item (text) values ('a libero nam dui');
insert into todo_item (text) values ('sed augue aliquam erat');
insert into todo_item (text) values ('augue vestibulum rutrum rutrum neque aenean');
insert into todo_item (text) values ('eu massa donec dapibus duis');
insert into todo_item (text) values ('vulputate luctus cum sociis natoque');
insert into todo_item (text) values ('at dolor quis odio consequat varius integer ac leo');
insert into todo_item (text) values ('sit amet lobortis sapien sapien non mi integer ac');
insert into todo_item (text) values ('aenean auctor gravida sem praesent');
insert into todo_item (text) values ('scelerisque quam turpis adipiscing lorem vitae');
insert into todo_item (text) values ('quis odio consequat varius integer ac leo');
insert into todo_item (text) values ('justo eu massa donec dapibus duis at velit eu');
insert into todo_item (text) values ('quis turpis sed ante');
insert into todo_item (text) values ('ipsum dolor sit amet consectetuer adipiscing');
insert into todo_item (text) values ('cursus vestibulum proin eu mi nulla ac enim');
insert into todo_item (text) values ('vestibulum ante ipsum primis in faucibus orci luctus et');
insert into todo_item (text) values ('curabitur convallis duis consequat dui nec nisi');
insert into todo_item (text) values ('dui luctus rutrum nulla');
insert into todo_item (text) values ('eget vulputate ut ultrices vel augue vestibulum ante');
insert into todo_item (text) values ('eget rutrum at lorem integer tincidunt');
insert into todo_item (text) values ('diam neque vestibulum eget vulputate');
insert into todo_item (text) values ('porttitor lacus at turpis donec');
insert into todo_item (text) values ('dignissim vestibulum vestibulum ante ipsum primis in faucibus');
insert into todo_item (text) values ('eget nunc donec quis');
insert into todo_item (text) values ('nulla dapibus dolor vel est donec odio');
insert into todo_item (text) values ('montes nascetur ridiculus mus vivamus');
insert into todo_item (text) values ('interdum mauris ullamcorper purus sit amet nulla quisque');
insert into todo_item (text) values ('ligula nec sem duis aliquam');
insert into todo_item (text) values ('non velit nec nisi vulputate nonummy');
insert into todo_item (text) values ('ipsum primis in faucibus orci luctus et ultrices');
insert into todo_item (text) values ('vestibulum rutrum rutrum neque aenean');
insert into todo_item (text) values ('quam a odio in hac habitasse platea');
insert into todo_item (text) values ('primis in faucibus orci luctus et ultrices posuere');
insert into todo_item (text) values ('fusce congue diam id ornare imperdiet');
insert into todo_item (text) values ('etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida');
insert into todo_item (text) values ('a nibh in quis justo maecenas rhoncus aliquam lacus');
insert into todo_item (text) values ('rhoncus aliquam lacus morbi quis tortor id');
insert into todo_item (text) values ('mattis nibh ligula nec sem');
insert into todo_item (text) values ('ridiculus mus vivamus vestibulum sagittis sapien cum');
insert into todo_item (text) values ('vulputate ut ultrices vel augue vestibulum');
insert into todo_item (text) values ('quis turpis sed ante');
insert into todo_item (text) values ('quis turpis eget elit sodales scelerisque mauris sit amet eros');
insert into todo_item (text) values ('in faucibus orci luctus et');
insert into todo_item (text) values ('justo in blandit ultrices enim');
insert into todo_item (text) values ('ut massa volutpat convallis morbi odio odio elementum');
insert into todo_item (text) values ('lacinia nisi venenatis tristique');
insert into todo_item (text) values ('dolor quis odio consequat varius');
insert into todo_item (text) values ('porttitor lacus at turpis donec posuere metus vitae ipsum aliquam');
insert into todo_item (text) values ('gravida nisi at nibh in');
insert into todo_item (text) values ('ultrices enim lorem ipsum dolor sit amet consectetuer');
insert into todo_item (text) values ('feugiat et eros vestibulum ac est lacinia nisi venenatis tristique');
insert into todo_item (text) values ('eget elit sodales scelerisque mauris sit amet eros suspendisse');
insert into todo_item (text) values ('leo odio condimentum id luctus');
insert into todo_item (text) values ('convallis tortor risus dapibus augue vel accumsan tellus nisi');
insert into todo_item (text) values ('donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin');
insert into todo_item (text) values ('justo aliquam quis turpis eget');
insert into todo_item (text) values ('in magna bibendum imperdiet');
insert into todo_item (text) values ('ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into todo_item (text) values ('imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed');
insert into todo_item (text) values ('sapien arcu sed augue aliquam erat volutpat in congue');
insert into todo_item (text) values ('convallis duis consequat dui nec nisi volutpat eleifend donec');
insert into todo_item (text) values ('aliquet ultrices erat tortor sollicitudin');
insert into todo_item (text) values ('nisl ut volutpat sapien');
insert into todo_item (text) values ('lorem ipsum dolor sit');
insert into todo_item (text) values ('massa id lobortis convallis tortor risus dapibus augue');
insert into todo_item (text) values ('iaculis congue vivamus metus arcu');
insert into todo_item (text) values ('in consequat ut nulla');
insert into todo_item (text) values ('posuere nonummy integer non velit donec diam');
insert into todo_item (text) values ('congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae');
insert into todo_item (text) values ('venenatis tristique fusce congue diam id ornare');
insert into todo_item (text) values ('imperdiet nullam orci pede venenatis');
insert into todo_item (text) values ('auctor sed tristique in tempus sit amet');
insert into todo_item (text) values ('scelerisque quam turpis adipiscing lorem vitae mattis nibh');
insert into todo_item (text) values ('eros viverra eget congue eget semper rutrum nulla');
insert into todo_item (text) values ('et ultrices posuere cubilia curae duis');
insert into todo_item (text) values ('sapien placerat ante nulla');
insert into todo_item (text) values ('at dolor quis odio consequat varius integer ac leo pellentesque');
insert into todo_item (text) values ('vulputate vitae nisl aenean lectus pellentesque eget nunc');
insert into todo_item (text) values ('odio curabitur convallis duis consequat');
insert into todo_item (text) values ('lacinia erat vestibulum sed magna at');
insert into todo_item (text) values ('odio curabitur convallis duis');
insert into todo_item (text) values ('sapien sapien non mi integer ac neque duis bibendum morbi');
insert into todo_item (text) values ('morbi a ipsum integer a nibh in');
insert into todo_item (text) values ('et eros vestibulum ac est lacinia nisi venenatis tristique');
insert into todo_item (text) values ('volutpat quam pede lobortis ligula sit amet eleifend pede libero');
insert into todo_item (text) values ('sit amet nunc viverra dapibus nulla suscipit ligula');
insert into todo_item (text) values ('dictumst maecenas ut massa quis augue luctus');
insert into todo_item (text) values ('amet eros suspendisse accumsan tortor quis');
insert into todo_item (text) values ('ridiculus mus etiam vel augue');
insert into todo_item (text) values ('massa quis augue luctus tincidunt nulla mollis molestie lorem');
insert into todo_item (text) values ('lacus at velit vivamus');
insert into todo_item (text) values ('adipiscing elit proin risus praesent lectus vestibulum');
insert into todo_item (text) values ('vehicula condimentum curabitur in');
insert into todo_item (text) values ('suspendisse potenti cras in purus eu magna');
insert into todo_item (text) values ('nisi nam ultrices libero non mattis');
insert into todo_item (text) values ('hendrerit at vulputate vitae nisl aenean');
insert into todo_item (text) values ('nisi at nibh in hac habitasse platea dictumst aliquam');
insert into todo_item (text) values ('mi sit amet lobortis sapien sapien non mi integer');
insert into todo_item (text) values ('sit amet sapien dignissim vestibulum vestibulum');
insert into todo_item (text) values ('quis turpis sed ante');
insert into todo_item (text) values ('at turpis a pede posuere nonummy integer non');
insert into todo_item (text) values ('sapien sapien non mi integer ac neque duis bibendum');
insert into todo_item (text) values ('ultrices phasellus id sapien in sapien iaculis congue');
insert into todo_item (text) values ('odio consequat varius integer ac leo pellentesque ultrices');
insert into todo_item (text) values ('sapien non mi integer ac neque');
insert into todo_item (text) values ('nulla neque libero convallis eget eleifend luctus ultricies eu');
insert into todo_item (text) values ('felis donec semper sapien a libero nam dui proin leo');
insert into todo_item (text) values ('viverra eget congue eget semper rutrum');
insert into todo_item (text) values ('posuere cubilia curae duis faucibus accumsan odio curabitur');
insert into todo_item (text) values ('est congue elementum in hac');
insert into todo_item (text) values ('consectetuer adipiscing elit proin');
insert into todo_item (text) values ('fusce posuere felis sed lacus morbi sem mauris laoreet');
insert into todo_item (text) values ('nunc viverra dapibus nulla suscipit');
insert into todo_item (text) values ('sit amet nunc viverra dapibus nulla suscipit ligula in');
insert into todo_item (text) values ('accumsan tellus nisi eu orci mauris lacinia sapien quis libero');
insert into todo_item (text) values ('nec condimentum neque sapien placerat');
insert into todo_item (text) values ('magna ac consequat metus sapien ut nunc');
insert into todo_item (text) values ('proin leo odio porttitor id');
insert into todo_item (text) values ('venenatis turpis enim blandit mi in porttitor pede');
insert into todo_item (text) values ('leo maecenas pulvinar lobortis est phasellus sit amet');
insert into todo_item (text) values ('magna ac consequat metus sapien ut nunc');
insert into todo_item (text) values ('aliquam convallis nunc proin at turpis a pede');
insert into todo_item (text) values ('at lorem integer tincidunt ante vel ipsum praesent blandit');
insert into todo_item (text) values ('consequat in consequat ut nulla sed accumsan felis ut');
insert into todo_item (text) values ('nec condimentum neque sapien placerat ante');
insert into todo_item (text) values ('consequat dui nec nisi volutpat');
insert into todo_item (text) values ('ultricies eu nibh quisque id justo sit amet');
insert into todo_item (text) values ('in quam fringilla rhoncus mauris enim leo');
insert into todo_item (text) values ('orci luctus et ultrices posuere cubilia');
insert into todo_item (text) values ('pellentesque volutpat dui maecenas tristique est et tempus semper est');
insert into todo_item (text) values ('justo aliquam quis turpis eget');
insert into todo_item (text) values ('proin risus praesent lectus vestibulum quam sapien varius ut');
insert into todo_item (text) values ('faucibus orci luctus et ultrices posuere cubilia');
insert into todo_item (text) values ('ut tellus nulla ut');
insert into todo_item (text) values ('dui luctus rutrum nulla tellus');
insert into todo_item (text) values ('turpis integer aliquet massa id');
insert into todo_item (text) values ('sit amet nunc viverra dapibus nulla');
insert into todo_item (text) values ('primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into todo_item (text) values ('quis libero nullam sit amet');
insert into todo_item (text) values ('nibh in hac habitasse platea dictumst aliquam');
insert into todo_item (text) values ('purus sit amet nulla quisque arcu libero rutrum ac lobortis');
insert into todo_item (text) values ('metus vitae ipsum aliquam');
insert into todo_item (text) values ('vitae nisl aenean lectus');
insert into todo_item (text) values ('dictumst aliquam augue quam');
insert into todo_item (text) values ('odio curabitur convallis duis consequat dui nec nisi volutpat eleifend');
insert into todo_item (text) values ('nunc proin at turpis a pede posuere nonummy');
insert into todo_item (text) values ('convallis nulla neque libero convallis eget eleifend luctus ultricies eu');
insert into todo_item (text) values ('consequat morbi a ipsum integer');
insert into todo_item (text) values ('mattis odio donec vitae nisi nam');
insert into todo_item (text) values ('maecenas tristique est et tempus semper est quam');
insert into todo_item (text) values ('enim leo rhoncus sed vestibulum sit amet cursus');
insert into todo_item (text) values ('mus vivamus vestibulum sagittis');
insert into todo_item (text) values ('congue vivamus metus arcu adipiscing molestie hendrerit at vulputate');
insert into todo_item (text) values ('dignissim vestibulum vestibulum ante ipsum primis');
insert into todo_item (text) values ('ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into todo_item (text) values ('ipsum primis in faucibus orci luctus et');
insert into todo_item (text) values ('venenatis tristique fusce congue diam');
insert into todo_item (text) values ('imperdiet sapien urna pretium');
insert into todo_item (text) values ('consequat varius integer ac leo pellentesque ultrices mattis odio donec');
insert into todo_item (text) values ('vestibulum quam sapien varius ut blandit non interdum');
insert into todo_item (text) values ('sem mauris laoreet ut');
insert into todo_item (text) values ('convallis eget eleifend luctus ultricies eu nibh');
insert into todo_item (text) values ('ut odio cras mi');
insert into todo_item (text) values ('quis libero nullam sit amet turpis elementum ligula vehicula consequat');
insert into todo_item (text) values ('congue vivamus metus arcu adipiscing molestie');
insert into todo_item (text) values ('ipsum ac tellus semper');
insert into todo_item (text) values ('aliquam augue quam sollicitudin vitae consectetuer');
insert into todo_item (text) values ('donec odio justo sollicitudin ut suscipit a feugiat et');
insert into todo_item (text) values ('augue aliquam erat volutpat in congue etiam');
insert into todo_item (text) values ('at turpis a pede posuere nonummy integer');
insert into todo_item (text) values ('pede justo eu massa donec');
insert into todo_item (text) values ('fermentum donec ut mauris eget');
insert into todo_item (text) values ('ac leo pellentesque ultrices mattis odio donec vitae nisi');
insert into todo_item (text) values ('convallis eget eleifend luctus ultricies eu nibh quisque id');
insert into todo_item (text) values ('interdum venenatis turpis enim blandit mi in porttitor pede justo');
insert into todo_item (text) values ('erat id mauris vulputate elementum nullam varius nulla facilisi cras');
insert into todo_item (text) values ('justo nec condimentum neque sapien placerat ante nulla justo');
insert into todo_item (text) values ('congue etiam justo etiam pretium');
insert into todo_item (text) values ('purus sit amet nulla quisque arcu libero');
insert into todo_item (text) values ('turpis integer aliquet massa id lobortis convallis tortor');
insert into todo_item (text) values ('rutrum neque aenean auctor gravida sem praesent id');
insert into todo_item (text) values ('ut tellus nulla ut erat id');
insert into todo_item (text) values ('lobortis vel dapibus at diam nam tristique tortor');
insert into todo_item (text) values ('nulla pede ullamcorper augue a suscipit nulla elit ac');
insert into todo_item (text) values ('in magna bibendum imperdiet nullam orci');
insert into todo_item (text) values ('volutpat dui maecenas tristique est et tempus semper');
insert into todo_item (text) values ('volutpat eleifend donec ut dolor');
insert into todo_item (text) values ('elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor');
insert into todo_item (text) values ('ut mauris eget massa tempor convallis nulla');
insert into todo_item (text) values ('eget nunc donec quis orci eget orci');
insert into todo_item (text) values ('primis in faucibus orci luctus');
insert into todo_item (text) values ('lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus');
insert into todo_item (text) values ('id massa id nisl venenatis lacinia aenean sit');
insert into todo_item (text) values ('ante vivamus tortor duis');
insert into todo_item (text) values ('diam vitae quam suspendisse');
insert into todo_item (text) values ('aliquam non mauris morbi non lectus aliquam sit amet');
insert into todo_item (text) values ('faucibus cursus urna ut');
insert into todo_item (text) values ('mattis nibh ligula nec sem duis aliquam convallis');
insert into todo_item (text) values ('justo lacinia eget tincidunt eget tempus vel pede');
insert into todo_item (text) values ('eget massa tempor convallis nulla neque libero');
insert into todo_item (text) values ('ut blandit non interdum in ante vestibulum');
insert into todo_item (text) values ('curae donec pharetra magna vestibulum');
insert into todo_item (text) values ('tellus nulla ut erat id mauris vulputate');
insert into todo_item (text) values ('a feugiat et eros');
insert into todo_item (text) values ('eleifend quam a odio in hac');
insert into todo_item (text) values ('blandit nam nulla integer pede justo lacinia eget');
insert into todo_item (text) values ('venenatis lacinia aenean sit amet justo');
insert into todo_item (text) values ('rhoncus dui vel sem sed sagittis nam congue risus');
insert into todo_item (text) values ('in consequat ut nulla sed accumsan felis ut at');
insert into todo_item (text) values ('justo maecenas rhoncus aliquam');
insert into todo_item (text) values ('eget congue eget semper rutrum nulla nunc');
insert into todo_item (text) values ('nec condimentum neque sapien');
insert into todo_item (text) values ('eget congue eget semper rutrum nulla');
insert into todo_item (text) values ('cubilia curae nulla dapibus dolor vel est donec');
insert into todo_item (text) values ('posuere cubilia curae donec pharetra');
insert into todo_item (text) values ('nisl venenatis lacinia aenean sit amet');
insert into todo_item (text) values ('sed sagittis nam congue risus semper');
insert into todo_item (text) values ('accumsan tellus nisi eu orci mauris lacinia sapien');
insert into todo_item (text) values ('justo nec condimentum neque sapien placerat ante nulla');
insert into todo_item (text) values ('duis bibendum felis sed');
insert into todo_item (text) values ('congue eget semper rutrum nulla nunc purus phasellus');
insert into todo_item (text) values ('nam nulla integer pede justo lacinia eget');
insert into todo_item (text) values ('faucibus orci luctus et');
insert into todo_item (text) values ('duis bibendum felis sed interdum venenatis turpis');
insert into todo_item (text) values ('varius integer ac leo pellentesque ultrices mattis odio donec vitae');
insert into todo_item (text) values ('mi integer ac neque duis');
insert into todo_item (text) values ('dui maecenas tristique est et tempus semper est');
insert into todo_item (text) values ('quisque erat eros viverra eget congue eget');
insert into todo_item (text) values ('imperdiet sapien urna pretium nisl ut volutpat');
insert into todo_item (text) values ('luctus nec molestie sed justo pellentesque');
insert into todo_item (text) values ('justo morbi ut odio cras mi pede malesuada in imperdiet');
insert into todo_item (text) values ('vehicula consequat morbi a ipsum');
insert into todo_item (text) values ('pede malesuada in imperdiet et commodo vulputate justo in blandit');
insert into todo_item (text) values ('morbi ut odio cras mi pede malesuada in imperdiet et');
insert into todo_item (text) values ('iaculis justo in hac habitasse platea dictumst etiam faucibus cursus');
insert into todo_item (text) values ('rutrum neque aenean auctor gravida sem');
insert into todo_item (text) values ('et tempus semper est quam pharetra magna ac consequat');
insert into todo_item (text) values ('ipsum primis in faucibus orci luctus et');
